### ISSUE TITLE
Неверная обработка действий клавиатуры

### ISSUE THREAD

**Issue by michDaven** [tieugene/iosc.py#163]
Отмечаю тут issue, которая обсуждалась. В процессе тестирования версии 0.1.1 выявлено, что при нажатии клавиш "влево", "вправо" клавиатуры каждое окно отображения аналогового или дискретного сигнала может быть смещено независимо от других сигналов, что неверно.

**Comment by tieugene** [comment]
Issue зафиксировно в #91

**Comment by tieugene** [comment]
keyPressEvent(), [eventFilter()](https://doc.qt.io/qt-5/eventsandfilters.html#event-filters)
