### ISSUE TITLE
X-zoom glitches

### ISSUE THREAD

**Issue by tieugene** [tieugene/iosc.py#203]

**Comment by michDaven** [comment]
Сейчас смотрю issues, которые здесь, в iosc.py. Эта issue #203 какая-то внутренняя для фиксации бага я так понимаю?

**Comment by tieugene** [comment]
> Сейчас смотрю issues, которые здесь, в iosc.py. Эта issue #203 какая-то внутренняя для фиксации бага я так понимаю?

Да. Горизонтальное масштабирование глючит если на старте сигнал растянут во всю ширину.
Несмертельно, нео неприятно.
